[package]
name = "opejson"
version = "0.2.0"
edition = "2021"
authors = ["Rhetro <rhetro@rhetroxc.com>"]
description = "Surgical JSON manipulation macros for Rust. (Strict, Genesis, and Law modes)"
license = "MIT"
repository = "https://github.com/rhetro/opejson"
readme = "README.md"
keywords = ["json", "macro", "dynamic", "serde_json", "auto-vivification"]
categories = ["data-structures", "encoding"]

[dependencies]
serde_json = "1.0"


[features]
default = []
law_mode = []
